### ISSUE TITLE
Use of tomllib (and not toml)

### ISSUE THREAD

**Issue by lstep** [AndrewVeee/nucleo-ai#7]
> I hope I don't regret choosing toml - it's supposed to be a simpler config format, but it's not used much.

To be honest I hate toml, not the format itself, but the fact that tomllib *only exists* in python >= 3.11. And most distributions still use python 3.10 (including me :-) as it's the remcommended stable (and for stable diffusion) version.
You can maybe use the toml module, instead of tomllib? Not sure if it's ok with python >= 3.11

_Originally posted by @AndrewVeee in https://github.com/AndrewVeee/nucleo-ai/issues/5#issuecomment-1948416658_

**Comment by AndrewVeee** [comment]
This looks like the best option. I'll give it a try soon!

**Comment by AndrewVeee** [comment]
Thanks! I'll definitely give this a try next week and try to get it out. I think without tomllib as a dependency, the app will work on a lot more python versions.

**Comment by AndrewVeee** [comment]
Switched to toml from tomllib and pushed the code. Hope this helps future installs!
