### ISSUE TITLE
Text is not visible in light mode on Windows

### ISSUE THREAD

**Issue by Runo888** [AndrewVeee/nucleo-ai#8]
Hey, I just got the program up and running on Windows (thanks again to @AndrewVeee for helping with troubleshooting!) and the website starts in light mode, but most of the text isn't visible. I was worried something was broken until I hit the dark mode switch in the top right. It seems like a lot of text is set to be white even in light mode.

I've tried this in Firefox and Chrome, and the problem seems to be consistent across the two browsers.

**Comment by AndrewVeee** [comment]
Thanks, someone else mentioned something similar. Next time I'm in windows, I'll give it a try. I default to light mode, so it's odd that it doesn't show up in Linux.

**Comment by AndrewVeee** [comment]
Ok, I think this is fixed.

I was able to reproduce it with Firefox set to dark mode in settings. I updated the styles so the body color style is set to var(--color) and it fixed it.
